[package]
name = "win-hotkeys"
version = "0.1.2"
license = "MIT"
repository = "https://github.com/iholston/win-hotkeys"
homepage = "https://github.com/iholston/win-hotkeys"
documentation = "https://docs.rs/win-hotkeys"
readme = "README.md"
description = "A simple thread safe rust library for system-wide hotkey management on Windows"
categories = ["os::windows-apis", "api-bindings"]
keywords = ["hotkey", "windows", "keyboard", "global", "win32"]
edition = "2021"

[package.metadata.docs.rs]
doc-scrape-examples = false

[dependencies]
windows = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
]}
thiserror = "2.0.4"
crossbeam-channel = "0.5.14"